Add workload identity to machmeter
cloudspannerecosystem/machmeter pull request #72
Opened 2023-04-19 09:59 UTC by manu2

2023-04-21 06:39 UTC, manitgupta commented
Places where doc updates are needed -

1. https://cloudspannerecosystem.dev/machmeter/requirements.html#setting-up-the-cloud-environment - We no longer need the service account based authentication. Please remove this section and add information about workload identity.
2. https://github.com/cloudspannerecosystem/machmeter/blob/master/README.md#installation - Setting service account should no longer be required
3. Wherever we are describing how workload identity works and what service accounts are created, please also define the permissions that are added to the roles.

Just do a quick-search to look for service account related documentation and change it accordingly, if I missed any.

Thank you for this awesome contribution! 🥂 🏆 !

2023-04-21 06:39 UTC, manitgupta requested changes

2023-04-21 06:39 UTC, manitgupta commented on docs/setup.md
> +| gkeConfig.kube_service_account                    | Name of GKE Service Account to be created                               |
We need to add a section here to briefly describe how Workload identity works and what is being done the creation of these accounts.

I will suggest add a subsection to this section - https://cloudspannerecosystem.dev/machmeter/setup.html#resource-creation-using-iaac

2023-04-24 09:06 UTC, manu2 commented on docs/setup.md
> +| gkeConfig.kube_service_account                    | Name of GKE Service Account to be created                               |
Done

2023-04-24 18:05 UTC, manitgupta approved these changes

2023-04-25 08:27 UTC, merged