Create install script to install dependencies
cloudspannerecosystem/machmeter pull request #73
Opened 2023-04-19 20:23 UTC by kinsaurralde

2023-04-20 03:15 UTC, manitgupta commented on install.sh
> +
Can we also add maven here?

2023-04-21 06:41 UTC, manitgupta requested changes
We should have Maven setup as part of this script.
If we can have JMeter setup as well that would be an awesome bonus.

2023-04-21 18:01 UTC, kinsaurralde commented on install.sh
> +
Added maven. Im not sure about JMeter, I dont remember installing it.

2023-04-23 19:08 UTC, manitgupta commented on install.sh
> +
I actually meant installing `mvn` and not building the project.
Building the project can live outside of the install script. Installation of maven can be part of it.

Ref -https://maven.apache.org/install.html

2023-04-24 18:04 UTC, manitgupta approved these changes

2023-04-25 09:02 UTC, manitgupta approved these changes

2023-04-26 04:33 UTC, merged